export const SCREEN_NAMES = {
  splash: "Splash",
  appintro: "App Intro",
  login: "Login",
  password: "Password",
  otp: "OTP",
  createpassword: "Create Password",
  passwordsuccess: "Password Success",
  welcome: "Welcome",
  fullname: "Full Name",
  birthday: "Birthday",
  designation: "Designation",
  dashboard: "Dashboard",
  home: "Home",
  profiles: "Profiles",
};
